/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ScaleUpRouteImport } from './routes/scale-up'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as WeekOnWeekRouteImport } from './routes/week-on-week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaleUpRoute = ScaleUpRouteImport.update({
  id: '/scale-up',
  path: '/scale-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekOnWeekRoute = WeekOnWeekRouteImport.update({
  id: '/week-on-week',
  path: '/week-on-week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/prompts': typeof PromptsRoute
  '/scale-up': typeof ScaleUpRoute
  '/scorecard': typeof ScorecardRoute
  '/setup': typeof SetupRoute
  '/week-on-week': typeof WeekOnWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/prompts': typeof PromptsRoute
  '/scale-up': typeof ScaleUpRoute
  '/scorecard': typeof ScorecardRoute
  '/setup': typeof SetupRoute
  '/week-on-week': typeof WeekOnWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/prompts': typeof PromptsRoute
  '/scale-up': typeof ScaleUpRoute
  '/scorecard': typeof ScorecardRoute
  '/setup': typeof SetupRoute
  '/week-on-week': typeof WeekOnWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiments'
    | '/login'
    | '/performance'
    | '/pipeline'
    | '/prompts'
    | '/scale-up'
    | '/scorecard'
    | '/setup'
    | '/week-on-week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiments'
    | '/login'
    | '/performance'
    | '/pipeline'
    | '/prompts'
    | '/scale-up'
    | '/scorecard'
    | '/setup'
    | '/week-on-week'
  id:
    | '__root__'
    | '/'
    | '/experiments'
    | '/login'
    | '/performance'
    | '/pipeline'
    | '/prompts'
    | '/scale-up'
    | '/scorecard'
    | '/setup'
    | '/week-on-week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentsRoute: typeof ExperimentsRoute
  LoginRoute: typeof LoginRoute
  PerformanceRoute: typeof PerformanceRoute
  PipelineRoute: typeof PipelineRoute
  PromptsRoute: typeof PromptsRoute
  ScaleUpRoute: typeof ScaleUpRoute
  ScorecardRoute: typeof ScorecardRoute
  SetupRoute: typeof SetupRoute
  WeekOnWeekRoute: typeof WeekOnWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scale-up': {
      id: '/scale-up'
      path: '/scale-up'
      fullPath: '/scale-up'
      preLoaderRoute: typeof ScaleUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week-on-week': {
      id: '/week-on-week'
      path: '/week-on-week'
      fullPath: '/week-on-week'
      preLoaderRoute: typeof WeekOnWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentsRoute: ExperimentsRoute,
  LoginRoute: LoginRoute,
  PerformanceRoute: PerformanceRoute,
  PipelineRoute: PipelineRoute,
  PromptsRoute: PromptsRoute,
  ScaleUpRoute: ScaleUpRoute,
  ScorecardRoute: ScorecardRoute,
  SetupRoute: SetupRoute,
  WeekOnWeekRoute: WeekOnWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
